<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-7OB19NV" failures="2" tests="2" name="Default test(failed)" time="1.126" errors="0" timestamp="2022-03-28T17:37:10 IST">
  <testcase classname="FailedTestNG.xml.FailedTesting" name="TC5" time="1.018">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method FailedTestNG.xml.FailedTesting.TC5() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method FailedTestNG.xml.FailedTesting.TC5() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TC5 -->
  <testcase classname="FailedTestNG.xml.FailedTesting" name="TC4" time="0.013">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at FailedTestNG.xml.FailedTesting.TC4(FailedTesting.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC4 -->
  <testcase classname="FailedTestNG.xml.FailedTesting" name="TC2" time="0.0">
    <ignored/>
  </testcase> <!-- TC2 -->
  <testcase classname="FailedTestNG.xml.FailedTesting" name="TC3" time="0.0">
    <ignored/>
  </testcase> <!-- TC3 -->
  <testcase classname="FailedTestNG.xml.FailedTesting" name="TC1" time="0.0">
    <ignored/>
  </testcase> <!-- TC1 -->
</testsuite> <!-- Default test(failed) -->
