<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-7OB19NV" failures="1" tests="2" name="Default test(failed)(failed)" time="0.098" errors="0" timestamp="2022-03-28T17:39:30 IST">
  <testcase classname="FailedTestNG.xml.FailedTesting" name="TC5" time="0.018"/>
  <testcase classname="FailedTestNG.xml.FailedTesting" name="TC4" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at FailedTestNG.xml.FailedTesting.TC4(FailedTesting.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC4 -->
  <testcase classname="FailedTestNG.xml.FailedTesting" name="TC2" time="0.0">
    <ignored/>
  </testcase> <!-- TC2 -->
  <testcase classname="FailedTestNG.xml.FailedTesting" name="TC3" time="0.0">
    <ignored/>
  </testcase> <!-- TC3 -->
  <testcase classname="FailedTestNG.xml.FailedTesting" name="TC1" time="0.0">
    <ignored/>
  </testcase> <!-- TC1 -->
</testsuite> <!-- Default test(failed)(failed) -->
